Course project in Programming Languages: Flight Class Reference
Flight Class Reference
Represents a flight, including its schedule, route, and assigned plane.
#include <flight.hpp>
Public Member Functions
bool assign_plane (const Plane &candidate)
Assigns a plane to the flight if it meets the necessary criteria.
bool set_from (const Airport &from)
Sets the origin airport for the flight.
bool set_to (const Airport &to)
Sets the destination airport for the flight.
double exhaust_rate () const
Calculates the workload for the pilot(s) during this flight.
double exhaust_rate (const Plane *_plane) const
Calculates the workload for a given plane during this flight.
double flight_duration () const
Calculates the flight duration based on the route length and plane speed.
double flight_duration (const Plane *) const
Calculates the flight duration based on the route length and plane speed.
Public Member Functions inherited from IEnumerable
IEnumerable ()
Default constructor. Assigns a unique ID to the instance.
virtual unsigned int get_id () const final
Retrieves the unique ID of the instance.
Friends
class AirSpaceManager
Declares AirSpaceManager as a friend class to access private members.
std::ostream & operator<< (std::ostream &out, const Flight &flight)
Overloaded output stream operator for Flight.
Detailed Description
Represents a flight, including its schedule, route, and assigned plane.
The Flight class encapsulates details about a specific flight, such as the takeoff time, route length, origin and destination airports, and the plane assigned to the flight. It also provides methods to calculate workload and flight duration.
Member Function Documentation
assign_plane()
bool Flight::assign_plane (const Plane & candidate)
Assigns a plane to the flight if it meets the necessary criteria.
Parameters
candidate The plane to be considered for assignment.
Returns
True if the plane was successfully assigned, false otherwise.
References Plane::can_land_on().
exhaust_rate() [1/2]
double Flight::exhaust_rate () const
Calculates the workload for the pilot(s) during this flight.
Returns
The workload as a percentage.
exhaust_rate() [2/2]
double Flight::exhaust_rate (const Plane * _plane) const
Calculates the workload for a given plane during this flight.
Parameters
_plane The plane to evaluate.
Returns
The workload as a percentage for the specified plane.
References Plane::get_average_speed().
flight_duration() [1/2]
double Flight::flight_duration () const
Calculates the flight duration based on the route length and plane speed.
Returns
The flight duration in hours.
References Plane::get_average_speed().
flight_duration() [2/2]
double Flight::flight_duration (const Plane * _plane) const
Calculates the flight duration based on the route length and plane speed.
Parameters
_plane The plane to evaluate.
Returns
The flight duration with the given plane in hours.
References Plane::get_average_speed().
set_from()
bool Flight::set_from (const Airport & from)
Sets the origin airport for the flight.
Parameters
from The airport object representing the flight's origin.
Returns
True if the origin was set successfully, false otherwise.
References Plane::can_land_on().
set_to()
bool Flight::set_to (const Airport & to)
Sets the destination airport for the flight.
Parameters
to The airport object representing the flight's destination.
Returns
True if the destination was set successfully, false otherwise.
References Plane::can_land_on().
Friends And Related Function Documentation
AirSpaceManager
friend class AirSpaceManager friend
Declares AirSpaceManager as a friend class to access private members.
operator<<
std::ostream& operator<< (std::ostream & out, const Flight & flight) friend
Overloaded output stream operator for Flight.
Parameters
out The output stream.
flight The Flight object to be output.
Returns
Reference to the output stream.
The documentation for this class was generated from the following files:
flight.hpp
flight.cpp