Course project in Programming Languages: Plane Class Reference
Plane Class Reference
Represents an aircraft with details for efficient airline management.
#include <plane.hpp>
Public Member Functions
bool can_land_on (const Airport &airport) const
Checks if the plane can land on a given airport.
double max_flight_distance () const
Calculates the maximum flight distance for the plane.
double get_average_speed () const
Retrieves the average speed of the plane.
Public Member Functions inherited from IEnumerable
IEnumerable ()
Default constructor. Assigns a unique ID to the instance.
virtual unsigned int get_id () const final
Retrieves the unique ID of the instance.
Friends
class AirSpaceManager
Declares AirSpaceManager as a friend class. Allows access to the private and protected members of Plane.
std::ostream & operator<< (std::ostream &out, const Plane &plane)
Overloaded output stream operator for Plane. Outputs the details of the plane to the provided stream.
Detailed Description
Represents an aircraft with details for efficient airline management.
The Plane class encapsulates data about the manufacturer, model, seating capacity, minimum runway length, operational costs, fuel consumption, tank volume, and average speed.
Member Function Documentation
can_land_on()
bool Plane::can_land_on (const Airport & airport) const
Checks if the plane can land on a given airport.
Parameters
airport The airport to check compatibility with.
Returns
True if the plane can land, false otherwise.
References Airport::get_lane_lengths().
Referenced by Flight::assign_plane(), Flight::set_from(), and Flight::set_to().
get_average_speed()
double Plane::get_average_speed () const
Retrieves the average speed of the plane.
Returns
The average speed in kilometers per hour.
Referenced by Flight::exhaust_rate(), and Flight::flight_duration().
max_flight_distance()
double Plane::max_flight_distance () const
Calculates the maximum flight distance for the plane.
Returns
The maximum distance the plane can travel in kilometers.
Friends And Related Function Documentation
AirSpaceManager
friend class AirSpaceManager friend
Declares AirSpaceManager as a friend class. Allows access to the private and protected members of Plane.
operator<<
std::ostream& operator<< (std::ostream & out, const Plane & plane) friend
Overloaded output stream operator for Plane. Outputs the details of the plane to the provided stream.
Parameters
out The output stream.
plane The plane object to be output.
Returns
Reference to the output stream.
The documentation for this class was generated from the following files:
plane.hpp
plane.cpp